server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /

# Dynamic DataSource Config
spring:
  application:
    name: buy-door-login-service

  datasource:
    username: root
    password: zaq12wsX
    url: jdbc:mysql://localhost:3306/whw_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    timeout: 6000
    # Redis服务器连接密码（默认为空）
    #password: 123456
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

#thymeleaf
  thymeleaf:
    prefix:
      classpath: /templates/
  suffix: .html
  mode: HTML5
  encoding: UTF-8
  cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**