
server:
  port: 9000
spring:
  application:
    name: buy-door-gateway-service
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: http://localhost:8080
          order: 1
          predicates:
            - Path=/mybatis_plus/**
          filters:
            - StripPrefix=1
    #nacos
    nacos:
      discovery:
        server-addr: 121.196.237.100:8848


#MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/whw_buy?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zaq12wsX
    driver-class-name: com.mysql.cj.jdbc.Driver